parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"Ztkr":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),t=require("react/jsx-runtime");function s(e,t,s){return t in e?Object.defineProperty(e,t,{value:s,enumerable:!0,configurable:!0,writable:!0}):e[t]=s,e}class i extends e.Component{constructor(...e){super(...e),s(this,"state",{active:0}),s(this,"handleIndexClick",e=>{this.setState({active:+e.target.dataset.index})})}render(){const{active:e}=this.state,{images:s}=this.props;return(0,t.jsxs)("div",{className:"pl-2 py-5 m-5 lg:m-20 flex flex-row justify-items-center align-items-center",children:[(0,t.jsx)("div",{className:"prof-cropper",children:(0,t.jsx)("img",{src:s[e],alt:"animal",className:"main-pic"})}),(0,t.jsx)("div",{className:"grid gap-2 gap-y-4 sm:grid-cols-2 lg:grid-cols-3 justify-items-center align-items-center px-10",children:s.map((s,i)=>(0,t.jsx)("div",{className:"image-cropper",children:(0,t.jsx)("img",{src:s,"data-index":i,onClick:this.handleIndexClick,className:i===e?"active":"",alt:"Animal Thumbnail"},s)}))})]})}}s(i,"defaultProps",{images:["http://pets-images.dev-apis.com/pets/none.jpg"]});var a=i;exports.default=a;
},{}],"mD05":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var r=require("react"),e=require("react-router-dom"),t=require("react/jsx-runtime");function o(r,e,t){return e in r?Object.defineProperty(r,e,{value:t,enumerable:!0,configurable:!0,writable:!0}):r[e]=t,r}class s extends r.Component{constructor(...r){super(...r),o(this,"state",{hasError:!1,redirect:!1})}static getDerivedStateFromError(){return{hasError:!0}}componentDidCatch(r,e){console.error("ErrorBoundary caught error",r,e)}componentDidUpdate(){this.state.hasError&&setTimeout(()=>this.setState({redirect:!0}),5e3)}render(){return this.state.redirect?(0,t.jsx)(e.Redirect,{to:"/"}):this.state.hasError?(0,t.jsxs)("h2",{children:["This listing has an error. ",(0,t.jsx)(e.Link,{to:"/",children:"Click here"})," to go back to Home or wait 5 sec."]}):this.props.children}}var i=s;exports.default=i;
},{}],"2tnM":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react");const t=(0,e.createContext)(["black",()=>{}]);var r=t;exports.default=r;
},{}],"KnKP":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),r=require("react-dom"),t=require("react/jsx-runtime");let u;const c=({children:c})=>{u=u||document.getElementById("modal");const n=(0,e.useRef)(null);return n.current||(n.current=document.createElement("div")),(0,e.useEffect)(()=>(u.appendChild(n.current),()=>u.removeChild(n.current)),[]),(0,r.createPortal)((0,t.jsx)("div",{children:c}),n.current)};var n=c;exports.default=n;
},{}],"C/Dc":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=u;var e=require("react"),t=require("react-router"),s=a(require("./Carousel")),r=a(require("./ErrorBoundary")),o=a(require("./ThemeContext")),i=a(require("./Modal")),n=require("react/jsx-runtime");function a(e){return e&&e.__esModule?e:{default:e}}function l(e,t,s){return t in e?Object.defineProperty(e,t,{value:s,enumerable:!0,configurable:!0,writable:!0}):e[t]=s,e}class d extends e.Component{constructor(...e){super(...e),l(this,"state",{loading:!0,showModal:!1}),l(this,"toggleModal",()=>this.setState({showModal:!this.state.showModal})),l(this,"adopt",()=>window.location="http://bit.ly/pet-adopt")}async componentDidMount(){const e=await fetch(`http://pets-v2.dev-apis.com/pets?id=${this.props.match.params.id}`),t=await e.json();this.setState(Object.assign({loading:!1},t.pets[0]))}render(){if(this.state.loading)return(0,n.jsx)("h2",{children:"Loading..."});const{animal:e,breed:t,city:r,state:a,description:l,name:d,images:c,showModal:u}=this.state;return(0,n.jsxs)("div",{className:"rounded-3xl p-1 m-5 lg:p-5 lg:mx-40 justify-items-center align-items-center block",style:{backgroundColor:"#f2e4e6"},children:[(0,n.jsx)(s.default,{images:c}),(0,n.jsxs)("div",{className:"px-0 mx-0 text-center justify-items-center align-items-center ",children:[(0,n.jsx)("h1",{className:"font-serif text-6xl",children:d}),(0,n.jsx)("h2",{className:"mb-5 font-sans text-2xl",children:`${e} - ${t} - ${r},${a}`}),(0,n.jsx)(o.default.Consumer,{children:([e])=>(0,n.jsxs)("button",{className:"rounded px-6 py-2 text-white hover:opacity-50 border-none",onClick:this.toggleModal,style:{backgroundColor:e},children:["Adopt ",d]})}),(0,n.jsx)("p",{className:"p-10 lg:my-50 text-lg",children:l}),u?(0,n.jsx)(i.default,{children:(0,n.jsxs)("div",{children:[(0,n.jsxs)("h1",{children:["Would you like to adopt ",d,"?"]}),(0,n.jsxs)("div",{className:"p-5",children:[(0,n.jsx)("button",{className:"rounded-xl px-6 py-2 m-5 text-white hover:opacity-50 border-none",style:{backgroundColor:"red"},onClick:this.adopt,children:"Yes"}),(0,n.jsx)("button",{className:"rounded-xl px-6 m-5 py-2 text-white hover:opacity-50 border-none",style:{backgroundColor:"red"},onClick:this.toggleModal,children:"No"})]})]})}):null]})]})}}const c=(0,t.withRouter)(d);function u(){return(0,n.jsx)(r.default,{children:(0,n.jsx)(c,{})})}
},{"./Carousel":"Ztkr","./ErrorBoundary":"mD05","./ThemeContext":"2tnM","./Modal":"KnKP"}],"/HkA":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=a;var e=require("react");const t=[];function a(a){const[s,n]=(0,e.useState)([]),[o,r]=(0,e.useState)("unloaded");return(0,e.useEffect)(()=>{a?t[a]?n(t[a]):async function(){n([]),r("loading");const e=await fetch(`http://pets-v2.dev-apis.com/breeds?animal=${a}`),s=await e.json();t[a]=s.breeds||[],n(t[a]),r("loaded")}():n([])},[a]),[s,o]}
},{}],"zx4L":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react-router-dom"),t=require("react/jsx-runtime");const r=({name:r,breed:s,animal:a,images:i,location:l,id:o})=>{let n="http://pets-images.dev-apis.com/pets/none.jpg";return i.length&&(n=i[0]),(0,t.jsxs)(e.Link,{to:`/details/${o}`,className:"relative block",children:[(0,t.jsx)("div",{children:(0,t.jsx)("img",{src:n,alt:r})}),(0,t.jsxs)("div",{className:"absolute bottom-0 left-0 bg-gradient-to-tr from-black to-transparent pr-2 pt-2 text-blue-300",children:[(0,t.jsx)("h1",{children:r}),(0,t.jsx)("h2",{children:`${a} - ${s} - ${l}`})]})]})};var s=r;exports.default=s;
},{}],"TZVW":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=t(require("./pet.js")),r=require("react/jsx-runtime");function t(e){return e&&e.__esModule?e:{default:e}}const i=({pets:t})=>(0,r.jsx)("div",{className:"grid gap-4 grid-cols-1 sm:grid-cols-1 lg:grid-cols-3",children:t.length?t.map(t=>(0,r.jsx)(e.default,{name:t.name,animal:t.animal,breed:t.breed,images:t.images,location:`${t.city},${t.state}`,id:t.id},t.id)):(0,r.jsx)("h2",{children:"No Pet found"})});var s=i;exports.default=s;
},{"./pet.js":"zx4L"}],"b+AF":[function(require,module,exports) {
"use strict";function e(e){return{type:"CHANGE_THEME",payload:e}}function t(e){return{type:"CHANGE_ANIMAL",payload:e}}function n(e){return{type:"CHANGE_BREED",payload:e}}function o(e){return{type:"CHANGE_LOCATION",payload:e}}Object.defineProperty(exports,"__esModule",{value:!0}),exports.changeAnimal=t,exports.changeBreed=n,exports.changeLocation=o,exports.changeTheme=e;
},{}],"n0tu":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),a=o(require("./useBreedList")),l=o(require("./result")),r=require("react-redux"),t=require("./actionCreators/changeTheme"),s=require("react/jsx-runtime");function o(e){return e&&e.__esModule?e:{default:e}}const c=["bird","cat","dog","rabbit"],n=()=>{const o=(0,r.useSelector)(e=>e.animal),n=(0,r.useSelector)(e=>e.location),i=(0,r.useSelector)(e=>e.breed),u=(0,r.useSelector)(e=>e.theme),[d,h]=(0,e.useState)([]),[m]=(0,a.default)(o),x=(0,r.useDispatch)();async function p(){const e=await fetch(`http://pets-v2.dev-apis.com/pets?animal=${o}&location=${n}&breed=${i}`),a=await e.json();h(a.pets)}function v(e){x((0,t.changeAnimal)(e.target.value)),x((0,t.changeBreed)(""))}return(0,e.useEffect)(()=>{p()},[]),(0,s.jsxs)("div",{className:"my-0 mx-auto w-5/6 flex flex-row",children:[(0,s.jsx)("div",{children:(0,s.jsxs)("form",{className:"p-10 mb-10 rounded-3xl shadow-lg flex flex-col justify-center items-center divide-y divide-gray-900",style:{backgroundColor:"#f2e4e6"},onSubmit:e=>{e.preventDefault(),p()},children:[(0,s.jsxs)("label",{className:"search-label",htmlFor:"location",children:["Location",(0,s.jsx)("input",{className:"search-control",id:"location",onChange:e=>x((0,t.changeLocation)(e.target.value)),value:n,placeholder:"Enter Location"})]}),(0,s.jsxs)("label",{className:"search-label",htmlFor:"Animal",children:["Animal",(0,s.jsxs)("select",{className:"search-control",id:"animal",value:o,onChange:v,onBlur:v,children:[(0,s.jsx)("option",{}),c.map(e=>(0,s.jsx)("option",{value:e,children:e},e))]})]}),(0,s.jsxs)("label",{className:"search-label",htmlFor:"Breed",children:["Breed",(0,s.jsxs)("select",{className:"search-control disabled:opacity-50",id:"breed",value:i,onChange:e=>x((0,t.changeBreed)(e.target.value)),onBlur:e=>x((0,t.changeBreed)(e.target.value)),children:[(0,s.jsx)("option",{}),m.map(e=>(0,s.jsx)("option",{value:e,children:e},e))]})]}),(0,s.jsxs)("label",{className:"search-label",htmlFor:"theme",children:["Theme",(0,s.jsxs)("select",{className:"search-control",value:u,onChange:e=>x((0,t.changeTheme)(e.target.value)),onBlur:e=>x((0,t.changeTheme)(e.target.value)),children:[(0,s.jsx)("option",{value:"darkblue",children:"Dark Blue"}),(0,s.jsx)("option",{value:"purple",children:"purple"}),(0,s.jsx)("option",{value:"black",children:"black"}),(0,s.jsx)("option",{value:"peru",children:"peru"}),(0,s.jsx)("option",{value:"mediumorchid",children:"mediumorchid"}),(0,s.jsx)("option",{value:"chartreuse",children:"chartreuse"})]})]}),(0,s.jsx)("button",{className:"rounded px-6 py-2 text-white hover:opacity-50 border-none",style:{backgroundColor:u},children:"Submit"})]})}),(0,s.jsx)("div",{className:"rounded-3xl p-10 mx-5 justify-items-center align-items-center",style:{backgroundColor:"#f2e4e6"},children:(0,s.jsx)(l.default,{pets:d})})]})};var i=n;exports.default=i;
},{"./useBreedList":"/HkA","./result":"TZVW","./actionCreators/changeTheme":"b+AF"}],"Vq8S":[function(require,module,exports) {
"use strict";function e(e="Seattle, WA",t){switch(t.type){case"CHANGE_LOCATION":return t.payload;default:return e}}Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=e;
},{}],"xcIY":[function(require,module,exports) {
"use strict";function e(e="dog",t){switch(t.type){case"CHANGE_ANIMAL":return t.payload;default:return e}}Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=e;
},{}],"5ozi":[function(require,module,exports) {
"use strict";function e(e="Havanese",t){switch(t.type){case"CHANGE_BREED":return t.payload;default:return e}}Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=e;
},{}],"ClMH":[function(require,module,exports) {
"use strict";function e(e="darkblue",t){switch(t.type){case"CHANGE_THEME":return t.payload;default:return e}}Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=e;
},{}],"5FKY":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("redux"),r=d(require("./location")),t=d(require("./animal")),u=d(require("./breed")),a=d(require("./theme"));function d(e){return e&&e.__esModule?e:{default:e}}var i=(0,e.combineReducers)({location:r.default,animal:t.default,breed:u.default,theme:a.default});exports.default=i;
},{"./location":"Vq8S","./animal":"xcIY","./breed":"5ozi","./theme":"ClMH"}],"olYk":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("redux"),r=t(require("./reducer/index"));function t(e){return e&&e.__esModule?e:{default:e}}const o=(0,e.createStore)(r.default,"object"==typeof window&&void 0!==window.__REDUX_DEVTOOLS_EXTENSION__?window.__REDUX_DEVTOOLS_EXTENSION__():e=>e);var _=o;exports.default=_;
},{"./reducer/index":"5FKY"}],"ffN9":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=u(require("react-dom")),r=require("react"),t=require("react-router-dom"),i=u(require("./Details")),s=u(require("./SearchParams")),a=require("react-redux"),d=u(require("./store")),l=require("react/jsx-runtime");function u(e){return e&&e.__esModule?e:{default:e}}const c=()=>(0,l.jsx)(r.StrictMode,{children:(0,l.jsx)(a.Provider,{store:d.default,children:(0,l.jsxs)("div",{style:{background:"url(http://pets-images.dev-apis.com/pets/wallpaperA.jpg)"},children:[(0,l.jsx)("header",{className:"w-full mb-10 text-center p-7 bg-gradient-to-b from-purple-400 via-pink-500 to-red-500",children:(0,l.jsx)(t.Link,{to:"/",className:"text-6xl text-white hover:text-gray-300",children:(0,l.jsx)("h1",{children:"Adopt Me!"})})}),(0,l.jsxs)(t.Switch,{children:[(0,l.jsx)(t.Route,{path:"/details/:id",children:(0,l.jsx)(i.default,{})}),(0,l.jsx)(t.Route,{path:"/",children:(0,l.jsx)(s.default,{})})]})]})})});var o=c;exports.default=o;
},{"./Details":"C/Dc","./SearchParams":"n0tu","./store":"olYk"}],"Focm":[function(require,module,exports) {
"use strict";var e=u(require("express")),t=require("react-dom/server"),r=require("react-router"),s=u(require("fs")),i=u(require("../src/app.js")),n=require("react/jsx-runtime");function u(e){return e&&e.__esModule?e:{default:e}}const d=process.env.PORT||3e3,o=s.default.readFileSync("dist/index.html").toString(),l=o.split("Not Rendered"),a=(0,e.default)();a.use("/dist",e.default.static("dist")),a.use((e,s)=>{s.write(l[0]);const u={},d=(0,n.jsx)(r.StaticRouter,{url:e.url,context:u,children:(0,n.jsx)(i.default,{})}),o=(0,t.renderToNodeStream)(d);o.pipe(s,{end:!1}),o.on("end",()=>{s.status(u||200),s.write(l[1]),s.end()})}),console.log(`listening on http://localhost:${d}`),a.listen(d);
},{"../src/app.js":"ffN9"}]},{},["Focm"], null)
//# sourceMappingURL=/index.js.map